### ISSUE TITLE
Web Viewer GUI

### ISSUE THREAD

**Issue by saulshanabrook** [timkpaine/perspective-python#27]
Does this support the GUI editor? https://jpmorganchase.github.io/perspective/docs/usage.html#perspective-viewer-web-component

**Comment by timkpaine** [comment]
There is no editor as yet, we're working on it

**Comment by timkpaine** [comment]
going to close this for now, there's some discussion pending with @afshin @texodus et al about a possible beakerx X perspective editable/pivotable/streamable one-grid-to-rule-them-all

**Comment by SimonBiggs** [comment]
That sounds awesome :)
